baseURL = "https://hugo-theme-island.netlify.app/"
languageCode = "en-us"
title = "ExampleSite"
description = "demo site of hugo-theme-island"
theme = "hugo-theme-island"
themesdir = "../.."

summaryLength = 128

# [menus]
#   [[menus.main]]
#     identifier = "menu.home"
#     name = "Home"
#     pageRef = "/"
#     weight = 10
#     [[menus.main.params]]
#       icon = "home"
#   [[menus.main]]
#     identifier = "menu.docs"
#     name = "Documents"
#     pageRef = "/docs"
#     weight = 20
#     [[menus.main.params]]
#       icon = "question-mark-circle"
#   [[menus.main]]
#     identifier = "menu.tags"
#     name = "Tags"
#     pageRef = "/tags"
#     weight = 30
#     [[menus.main.params]]
#       icon = "tag"
#   [[menus.main]]
#     identifier = "menu.archives"
#     name = "Archives"
#     pageRef = "/archives"
#     weight = 40
#     [[menus.main.params]]
#       icon = "archive-box"
#   [[menus.main]]
#     identifier = "menu.authors"
#     name = "Authors"
#     pageRef = "/authors"
#     weight = 50
#     [[menus.main.params]]
#       icon = "user-circle"

[languages]
  [languages.en]
    disabled = false
    languageCode = "en"
    # languageDirection = ""
    languageName = "English"
    weight = 0
    title = "ExampleSite"
    [languages.en.params]
      logo = "demo-logo.png"
      dateFormat = "Jan 02"
      description = "demo site of hugo-theme-island"
  [languages.zh-CN]
    disabled = false
    languageCode = "zh-CN"
    # languageDirection = ""
    languageName = "中文"
    title = "示例网站"
    weight = 10
    [languages.zh-CN.params]
      logo = "demo-logo.png"
      dateFormat = "01-02"
      description = "hugo-theme-island 主题示例以及文档"

[pagination]
  disableAliases = false
  pagerSize = 5
  path = "page"

[permalinks]
  authors = "/u/:slug/"

[Taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[params]
  logo = "demo-logo.png"
  mainSections = ["docs"]
  dateFormat = "01/02"
  description = "xxx"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
      [markup.highlight]
        style = "github"
        noClasses = false
