[[main]]
  identifier = "menu.home"
  name = "主页"
  pageRef = "/"
  weight = 10
    [[main.params]]
      icon = "home"
[[main]]
  identifier = "menu.docs"
  name = "文档"
  pageRef = "/docs"
  weight = 20
    [[main.params]]
      icon = "question-mark-circle"
[[main]]
  identifier = "menu.tags"
  name = "标签"
  pageRef = "/tags"
  weight = 30
    [[main.params]]
      icon = "tag"
[[main]]
  identifier = "menu.archives"
  name = "归档"
  pageRef = "/archives"
  weight = 40
    [[main.params]]
      icon = "archive-box"
[[main]]
  identifier = "menu.authors"
  name = "作者"
  pageRef = "/authors"
  weight = 50
    [[main.params]]
      icon = "user-circle"
[[main]]
  identifier = "menu.github"
  name = "hugo-theme-island Github 仓库"
  url = "https://github.com/bin16/hugo-theme-island"
  weight = 50
    [[main.params]]
      icon = "bs/github"
      target = "_blank"
